=== jingtao/WebJuTuan/res/hao123.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified">
	<!-- 商品URLurl 256 bytes ［必填］ -->
	<xs:element name="loc" type="xs:string" default="" />
	<!-- 站点名称 50 bytes ［必填］ -->
	<xs:element name="website" type="xs:string" default="" />
	<!-- 各城市对应的页面url ［必填］ 如此处应为http://xxx.baidu.com/beijing/ 256 bytes  -->
	<xs:element name="siteurl" type="xs:string" default="" />
	<!-- 城市名称 ［必填］（城市名称不需要附带省、市、区、县等字，如果是全国范围请指明：全国） 16 bytes  -->
	<xs:element name="city" type="xs:string" default="" />
	<!-- 团购商家的大众点评shopid，多个以英文逗号分隔,512 bytes ［值可以为，字段必须有］ -->
	<xs:element name="dpshopid" type="xs:string" default="" />
	<!-- 团购商家的大概方位，多个以英文逗号分隔，按照填写顺序显示商家,512 bytes［值可为空，字段必须有］-->
	<xs:element name="range" type="xs:string" default="" />
	<!-- 团购商家的具体位置，多个以英文逗号分隔，按照填写顺序显示商家,2048 bytes［值可为空，字段必须有］-->
	<xs:element name="address" type="xs:string" default="" />
	<!-- 商品标题 512 bytes［必填］ -->
	<xs:element name="title" type="xs:string" default="" />
	<!-- 商品图片url 256 bytes ［必填］ -->
	<xs:element name="image" type="xs:string" default="" />

	<!--同一个城市如果推出多个团购商品，需要设置其中一款商品为今日主打商品，主打商品的这个字段是为1,非主打商品为0, 1bytes [值可为空，字段必须有] -->
	<xs:element name="major" type="xs:integer" default="0" />
	<!-- 团购分类 1=餐饮美食，2=休闲娱乐，3=美容化妆，4=网上购物，5=运动健身, 4 bytes [如果不能确定分类，值可以为，字段必须有] -->
	<xs:element name="category" type="xs:integer" default="0" />
	<!-- 商品开始时间 10 bytes ［必填］ -->
	<xs:element name="startTime" type="xs:integer" default="0" />
	<!-- 商品结束时间 10 bytes ［必填］ -->
	<xs:element name="endTime" type="xs:integer" default="0" />
	<!-- 已购买人数 10 bytes ［必填］ -->
	<xs:element name="bought" type="xs:integer" default="0" />

	<!-- 商品原价 12 bytes ［必填］ -->
	<xs:element name="value" type="xs:decimal" default="0.0" />
	<!-- 商品现价 12 bytes ［必填］ -->
	<xs:element name="price" type="xs:decimal" default="0.0" />
	<!-- 商品折扣 6 bytes ［必填］ -->
	<xs:element name="rebate" type="xs:decimal" default="0.0" />

	<xs:element name="display">
		<xs:complexType>
			<xs:all>
				<xs:element ref="website" />
				<xs:element ref="siteurl" />
				<xs:element ref="city" />
				<xs:element ref="dpshopid" />
				<xs:element ref="range" />
				<xs:element ref="address" />
				<xs:element ref="title" />
				<xs:element ref="image" />
				<xs:element ref="major" />
				<xs:element ref="category" />
				<xs:element ref="startTime" />
				<xs:element ref="endTime" />
				<xs:element ref="bought" />
				<xs:element ref="value" />
				<xs:element ref="price" />
				<xs:element ref="rebate" />
			</xs:all>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="data">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="display" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="url">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="loc" />
				<xs:element ref="data" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="urlset">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="url" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

</xs:schema>

=== jingtao/WebJuTuan/res/hao123sample.xml
<?xml version="1.0" encoding="utf-8" ?>
<urlset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:schemaLocation="hao123.xsd">
	<url>
		<loc>http://xxx.baidu.com/xxxxxx</loc>
		<!-- 商品URLurl 256 bytes ［必填］ -->
		<data>
			<display>
				<website>美团</website>
				<!-- 站点名称 50 bytes ［必填］ -->
				<siteurl>http://xxx.baidu.com</siteurl>
				<!-- 站点名称（请填写各城市对应的页面url，如此处应为http://xxx.baidu.com/beijing/） 256 bytes 
					［必填］ -->
				<city>北京</city>
				<!-- 城市名称（城市名称不需要附带省、市、区、县等字，如果是全国范围请指明：全国） 16 bytes ［必填］ -->
				<category>1</category>
				<!-- 团购分类 1=餐饮美食，2=休闲娱乐，3=美容化妆，4=网上购物，5=运动健身, 4 bytes [如果不能确定分类，值可以为，字段必须有] -->
				<dpshopid>507810, 2218060</dpshopid>
				<!-- 团购商家的大众点评shopid，多个以英文逗号分隔,512 bytes ［值可以为，字段必须有］-->
				<range>三里屯,中关村</range>
				<!-- 团购商家的大概方位，多个以英文逗号分隔，按照填写顺序显示商家,512 bytes［值可为空，字段必须有］-->
				<address>北京市三里屯XX路XX大厦,中关村YY路XX广场</address>
				<!-- 团购商家的具体位置，多个以英文逗号分隔，按照填写顺序显示商家,2048 bytes［值可为空，字段必须有］-->
				<major>1</major>
				<!--同一个城市如果推出多个团购商品，需要设置其中一款商品为今日主打商品，主打商品的这个字段是为1,非主打商品为0, 1bytes [值可为空，字段必须有] -->
				<title>原价188元的“玛雅蛋糕”仅售49元！</title>
				<!-- 商品标题 512 bytes［必填］ -->
				<image>http://maya.xxx.com/xxx.gif</image>
				<!-- 商品图片url 256 bytes ［必填］ -->
				<startTime>1275926400</startTime>
				<!-- 商品开始时间 10 bytes ［必填］ -->
				<endTime>1291910399</endTime>
				<!-- 商品结束时间 10 bytes ［必填］ -->
				<value>188.00</value>
				<!-- 商品原价 12 bytes ［必填］ -->
				<price>49.00</price>
				<!-- 商品现价 12 bytes ［必填］ -->
				<rebate>2.6</rebate>
				<!-- 商品折扣 6 bytes ［必填］ -->
				<bought>100</bought>
				<!-- 已购买人数 10 bytes ［必填］ -->
			</display>
		</data>
	</url>
</urlset>
